### ISSUE TITLE
Feature request: Automatic linking

### ISSUE THREAD

**Issue by Kullenej** [dalcantara7/obsidian-auto-moc#3]
A feature request for a automatic linking whenever there is unlinked mentions.

**Comment by dalcantara7** [comment]
Could you elaborate on how you expect this to work? 

Is it something like: you open up a note and the missing links are immediately added at the note?
Or is it more: when you create a link to a note, in the background it goes and adds the backlink to the linked note?

Or is it something else entirely?

**Comment by Kullenej** [comment]
Hmm.. Not quite sure how it best could be implemented, but the idea is that you need some automation since the plugin help with something you tend to forget to do. So here I am thinking that the plugin helps me do something I otherwise would forget. I guess it would be fine that it happened everytime I opened a note.

**Comment by dalcantara7** [comment]
So I thought about this when first creating the extension, but there are problems with making this useful to different users.

For example, just the problem of where to put the links in the notes is a complex one. Should they just be added to the top of the note? The bottom? Should the user be able to define their own heading or keyword under which the links are added? 

What about triggers? Should this happen automatically? When the note is opened? Only when the user commands it? Some users may want it to happen automatically most times, but not others.

Which notes should it be added to? Should it only be added to notes that the user considers a MOC? How do you standardize what is a MOC so that any user who downloads this plugin knows which structure to use? And what about users that don't want to conform to that standard? How can we accommodate them? Even if we make the link automatically, the user still has to go in and move the link to where they want it in the note so it still requires manual work.

This is why it was easier to design the plugin as it is now. The user only triggers it on the notes they want to. They can define exactly where the links are added (via where they place their cursor). It's flexible enough that we don't have to force any user into some standard. Because the user is already in the note where they want to add the links, they have the incentive to move the links exactly where they want them at the time that they run the plugin.

The framing of this plugin is as a tool to help you identify missing links *after the fact*. Doing it beforehand (i.e. automatically) adds a lot of needless complexity to an otherwise simple use case fix. 

I say all this not because I don't want to build it, but more so because the juice doesn't seem worth the squeeze. This functionality plugs one hole, but creates several others that aren't trivial to solve. 

So this needs more specification on how to make it robust for a general user

**Comment by dalcantara7** [comment]
Closing this as won't fix (for now). If there is high demand for this in the future (and I can get some help working out the details). I may reopen this and consider implementing it
