### ISSUE TITLE
Feature request: When creating a MOC from tags, link to the tagged heading directly

### ISSUE THREAD

**Issue by fanis** [dalcantara7/obsidian-auto-moc#8]
_(This might be slightly similar to Issue #4)_
I wonder if AutoMOC can be changed (perhaps behind a disabled option) to also suffix in its file links the heading that includes the queried tag. As it is now, AutoMOC creates an index with links to the files only, not the actual heading. 

I have long files with multiple headings (H2) in them, all tagged with various tags. I want to create an index of links to headings for a specific tag.

Would this be possible?

**Comment by dalcantara7** [comment]
So is your suggestion like #4, but for tags instead of linked mentions?

**Comment by dalcantara7** [comment]
Hi sorry for the late response, was very busy last week.

My goal with this extension is just to be able to create a MOC to have central place for all notes centered around a theme or tag. Kind of like an index as you described, but not a full Table of Contents. I just want to set the scope clearly.  

Could you give me an example index file and example file that would appear in that index? I'm still not fully understanding how what you're wanting is different than #4. 

Is it something like if (tag in this file) AND (under an h2) then make link to file.h2?

**Comment by dalcantara7** [comment]
Okay so I've been thinking on how to implement this so that other users can get value from it to (and not just tailor a specific solution).

I'm thinking I'll add an option like "Link to specific heading" that is binary. If it's on, once you run the find linked mentions or find tagged files function, a secondary popup appears before running asking which heading you want to link to. It will then search for that heading in the document (find the closest one above where the link/tag is) and then create the link to that heading.

Since this extension is designed to run as a batch it's possible not all of the files that will be linked will have the corresponding heading. If a file doesn't have the corresponding heading, it will just link to the file itself (no heading).

There's many different ways users will structure their files, but I think this creates a nice balance between robustness and solving the problem you're describing. Does this seem like an appropriate solution?

**Comment by dalcantara7** [comment]
@fanis Sorry for such a long time between updates. I had some stuff come up that kept me busy. I have just released a new version of AutoMOC with support for your ask. I ended up not going with the "link to specific heading type" idea and went with a simple "closest heading approach". Please test the plugin and report any issues you encounter. I hope the update will address your use case. I will close this feature request for now.

**Comment by fanis** [comment]
Diego, appreciated and will test now. 

Perhaps I'm doing something wrong but I can't seem to get it to work. Steps:

- I enabled the new option toggle (`Link to heading`) in AutoMOC options.
- I open the note called "2023" where I have hundreds of target lines (H2 heading, in the same line as the task title I have tags like `#todo`)
- I go to the command palette and select "AutoMOC: Add missing notes with specific tag at the current cursor location"
- A dialog comes up asking for the tag, I type "#todo" which also autocompletes from the list of existing tags
- A notice comes up saying "Linking mentions"
- Another notice comes up saying "No new linked notes found"

I also did the same in a new file in the same folder as my note.

**Comment by dalcantara7** [comment]
Ah, forgive me. I implemented support for YAML frontmatter tags which don't use "#" before the tag name and tested primarily with that, so it wasn't matching tags with "#". I have handled this now. Please uninstall and reinstall the plugin and try again. You cannot update the plugin. An uninstall is needed.

The other thing of note, is that when a tag is on the same line as a heading, the anchor link to the heading will _have_ to be in the link. Otherwise, obsidian can't resolve the link. So for example, if I have a heading
#My Heading #todo in file "Example"

Then the link will be created as [[Example#My Heading todo]]. As I understand it, there is no way around this. I hope this is okay.

Do let me know if you encounter anymore bugs

**Comment by fanis** [comment]
Reinstalled and tested on a file shown below, with the result printed further down.

It is linking them correctly (though I'd love to be able to have a toggle to remove all the detected tags) but it is only linking the first one found.

```


# 2023-07-24

## Task 1 #priority/highest  #todo 

---------------------


## Task 2 #priority/medium  #todo 

---------------------


# 2023-07-25


## Task 3 #priority/low #todo 

---------------------


# Automoc test

[[#Task 1 priority/highest  todo]]
[[#Task 1 priority/highest  todo]]
[[#Task 1 priority/highest  todo]]
```

**Comment by dalcantara7** [comment]
So on the optional toggle. Unfortunately there is no way to properly link to the section without also including the tags. Otherwise it breaks the link and Obsidian can't resolve where in the document to link to. One way around this would be to put your tags on the line immediately below the heading. That way Obsidian sees the link as only including the heading, not the tag.

For the multiple headings per document, I see the issue, but will need time to implement it. I will try to work on it next week

**Comment by dalcantara7** [comment]
Hi Fanis,

I have updated the code with release 1.3.1 to support multiple tags in a single file. Please update the plugin and test to let me know it is working properly.

Thanks

**Comment by fanis** [comment]
Hi Diego, this looks good now - I will test it out a bit more but it seems to be picking up and linking the right H2s. If I spot something I will revert on this thread.

Thanks!

**Comment by dalcantara7** [comment]
Sure thing. Going to close this thread now.
